### ISSUE TITLE
None Valid Parameters issue

### ISSUE THREAD

**Issue by jonangel0** [SmugBlanco/ImagePaintings#1]
There is an issue where where whenever I try to do the painting command, it always comes up with the non valid parameters text, not placing down the painting.

![image](https://user-images.githubusercontent.com/59521511/100405011-b77e4000-3030-11eb-9662-313b7bf44977.png)

(Edit: I typed in the text after the issue appeared to just show you how I have been typing it in).

**Comment by Smug-B** [comment]
Dont include angle brackets ( these things -> <> ) when typing in the commands, I probably should've been clearer about that.
Example of a valid command: 
/painting https://www.theregreview.org/wp-content/uploads/2019/11/gobble.jpg 5 5

A General Note: The mod has been discovered to break on the 64 bit version of tMod. So if you're on that then :(. 
A patch will come soon
