### ISSUE TITLE
What kind of image websites can we use? 

### ISSUE THREAD

**Issue by MyUsernameMaka** [SmugBlanco/ImagePaintings#2]
"I love the concept of this mod, but I am curious as to which websites I should get an image from and what url shortener I should use. I've tried using Imgur and gettyimages as image sources, yet they have not works. Thank you so much for putting this mod out there and have a great day!"

Realized I wrote this in the wrong area woops.

Update: I was using 64bit, but I still am curious as do imgur and other image hosting websites work as well?

**Comment by Smug-B** [comment]
Any link that when opened, takes you to an image should work. Redirects may take longer to process ( Ex being using an image shortener such as bitly ); but during my rounds of testing they seem to work. 

Only issues with links I can see terraria's chat system bugging out if the link is too long. Or if the image is not in a supported encoding such as gifs.
